
CREATE TABLE produto
(
  id int8 NOT NULL,
  codigodofabricante text,
  ean text,
  dun text,
  marca text,
  fabricante text,
  nome text,
  descricao text,
  ncm text,
  cest text,
  codigodamontadora jsonb,
  codigossimilares jsonb,
  curvaabc text,
  linha text,
  unidadedemedida text,
  quantidadenacaixa integer,
  quantidademinimadevenda integer,
  alturadacaixa numeric,
  larguradacaixa numeric,
  comprimentodacaixa numeric,
  alturadaembalagem numeric,
  larguradaembalagem numeric,
  comprimentodaembalagem numeric,
  alturadoproduto numeric,
  larguradoproduto numeric,
  comprimentodoproduto numeric,
  pesodacaixa text,
  pesodaembalagem text,
  pesoliquidodoproduto text,
  pesobrutodoproduto text,
  outrasinformacoes jsonb,
  categoriauniversalsmartpeca jsonb,
  categoriafonte jsonb,
  categoriags1 jsonb,
  aplicacaouniversalsmartpeca jsonb,
  aplicacaodafonte jsonb,
  status text,
  garantia text,
  sinonimo text,
  preco text,
  crosssell text,
  codigounico text,
  imagem oid,
  CONSTRAINT produto_pkey PRIMARY KEY (id)
);